<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Repeat password_repeatedPassword</name>
   <tag></tag>
   <elementGuidId>15d66899-8da1-4061-82ac-d88f74c35823</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='repeatedPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;repeatedPassword&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;repeatedPassword&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bfbdaaa6-7393-4cf3-9a9d-bf41da2e510e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repeatedPassword</value>
      <webElementGuid>297aa0b6-44dd-4abb-bfb1-1605d5b1544c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>09036090-af21-4c74-8c7c-03f947a33706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Catalog&quot;)/form[1]/table[1]/tbody[1]/tr[3]/td[2]/input[1]</value>
      <webElementGuid>6b7a7be6-e064-4733-9a4d-f646d2030e92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='repeatedPassword']</value>
      <webElementGuid>1a6c54b7-9f86-4c4a-b985-8b128477478b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Catalog']/form/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>f1761344-dc7f-41ce-8dbe-ad60319a0a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>81d42ddc-f296-4d2e-854d-687fb5c111af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'repeatedPassword' and @type = 'text']</value>
      <webElementGuid>c1edb972-9422-4aa1-901b-064d93c6ef4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
