<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img (1)</name>
   <tag></tag>
   <elementGuidId>38de0ec0-bda8-4126-9890-8c03c459bcff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='QuickLinks']/a[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(2) > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#QuickLinks >> internal:role=link >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>49517143-b737-43ae-899d-5cb1fd704af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/sm_dogs.gif</value>
      <webElementGuid>2a10af28-5b59-4c09-9015-6984a9226be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QuickLinks&quot;)/a[2]/img[1]</value>
      <webElementGuid>191897d6-3713-4c13-ad9e-2be5fe11f4dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='QuickLinks']/a[2]/img</value>
      <webElementGuid>917fbadb-f088-4b45-8376-60ded9de8ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>f25f6ff9-82da-43f8-ae83-ab39533dcb27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images/sm_dogs.gif']</value>
      <webElementGuid>3f3a45cb-059e-465e-8ceb-4519b3facda6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
