<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Repeat password_repeatedPassword</name>
   <tag></tag>
   <elementGuidId>cd9d2f48-cc8f-4680-a325-122ebe7474ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='repeatedPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;repeatedPassword&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;repeatedPassword&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3242016f-5db8-4b87-a015-1fd679553586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repeatedPassword</value>
      <webElementGuid>6d977c4e-283f-4a98-96c5-489ccb4a1d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>51ab0330-b361-4919-aa9c-5d410b979681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Catalog&quot;)/form[1]/table[1]/tbody[1]/tr[3]/td[2]/input[1]</value>
      <webElementGuid>a83f6daa-d2ad-43dd-a14d-66e367fffc73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='repeatedPassword']</value>
      <webElementGuid>1421932b-1617-4e2b-8f53-4f8aca0b513d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Catalog']/form/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>69644ac6-90df-4ecf-8363-d3eeca47470e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>0ee11d82-934c-413a-85c1-1c59425f4ff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'repeatedPassword' and @type = 'text']</value>
      <webElementGuid>cf9bf955-a83d-4521-80b5-afb1f1618bfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
