<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_FISHDOGSREPTILESCATSBIRDS</name>
   <tag></tag>
   <elementGuidId>e635afa2-fe65-4c06-8112-0843b9f36508</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='account.favouriteCategoryId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;account.favouriteCategoryId&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;account\.favouriteCategoryId&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>49fd508f-e281-4afe-ad80-979a0663e900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account.favouriteCategoryId</value>
      <webElementGuid>9bf60bd0-1918-4a23-a92c-ee35857fa8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			FISHDOGSREPTILESCATSBIRDS
		</value>
      <webElementGuid>f5a52259-34aa-4846-8970-c721ca922747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Catalog&quot;)/form[1]/table[3]/tbody[1]/tr[2]/td[2]/select[1]</value>
      <webElementGuid>a1c723b7-eafb-4b25-b5eb-540c72d13a4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='account.favouriteCategoryId']</value>
      <webElementGuid>ea938a9f-3be9-4a0c-965e-8ca416cf50ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Catalog']/form/table[3]/tbody/tr[2]/td[2]/select</value>
      <webElementGuid>67c0a71a-3ac9-4606-8867-a6951b710db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Favourite Category:'])[1]/following::select[1]</value>
      <webElementGuid>9b09c2ba-326f-4eb4-a096-e9f76fbbc61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language Preference:'])[1]/following::select[2]</value>
      <webElementGuid>dd366fff-e083-4353-87e4-2d05fea4f431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable MyList'])[1]/preceding::select[1]</value>
      <webElementGuid>42fb85f2-7794-4a49-8264-6c7ed1a0c46f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable MyBanner'])[1]/preceding::select[1]</value>
      <webElementGuid>727f0e39-2b9b-4f1e-aee0-5ea4300cb2ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/select</value>
      <webElementGuid>57e8eb43-e153-4dd5-8421-cfb9d3136f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'account.favouriteCategoryId' and (text() = '
			FISHDOGSREPTILESCATSBIRDS
		' or . = '
			FISHDOGSREPTILESCATSBIRDS
		')]</value>
      <webElementGuid>0d558e89-6c41-49b1-9eaa-2aa714dba12d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
